//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IlizaGalina321_PetMoments.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id_users { get; set; }
        public string Username { get; set; }
        public string Role { get; set; }
        public string password { get; set; }
        public string Photo { get; set; }
    }
}
